---
# https://fluxcd.io/docs/components/source/helmrepositories/
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: confluentinc
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://packages.confluent.io/helm
---
# https://fluxcd.io/docs/components/helm/helmreleases/
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: confluent-operator
  namespace: flux-system
spec:
  releaseName: confluent-operator
  install:
    createNamespace: true
  targetNamespace: confluent
  chart:
    spec:
      chart: confluent-for-kubernetes
      sourceRef:
        kind: HelmRepository
        name: confluentinc
  values:
    podSecurity:
      enabled: false
    namespaced: false
    rbac: false
  interval: 1m0s