apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: teamx
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: teamx-git
  url: ssh://git@github.com/in-the-keyhole/gitops-teamx
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: teamx
spec:
  interval: 1m0s
  path: # set by env overlay
  prune: true
  sourceRef:
    kind: GitRepository
    name: teamx
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: teamx-image-update
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: teamx
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      # This can be changed to push to different branch and utilize pull request process
      branch: flux-production-image-updates
  update:
    path: # set by env overlay
    strategy: Setters