apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: team1
spec:
  path: ./staging
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: team1-image-update
spec:
  git:
    push:
      branch: main
  update:
    path: ./staging