# https://fluxcd.io/docs/components/kustomize/kustomization/
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: production-operators
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./operators/production
  prune: true
  wait: false
  timeout: 1m0s