---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: teamx
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/in-the-keyhole/gitops-teamx
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: teamx-production
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./production
  prune: true
  sourceRef:
    kind: GitRepository
    name: teamx
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: teamx-staging
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: teamx
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: teamx-develop
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./develop
  prune: true
  sourceRef:
    kind: GitRepository
    name: teamx