# https://fluxcd.io/docs/components/kustomize/kustomization/
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: production-tenants
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: production-infrastructure
  serviceAccountName: kustomize-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenants/production
  prune: true