apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: teamx
spec:
  path: ./develop
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: teamx-image-update
spec:
  git:
    push:
      branch: main
  update:
    path: ./develop