---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: teamx-git
  namespace: flux-system
spec:
  encryptedData:
    identity: AgAFp4Bl4E3JJUxox1R/qmiJFqAKKwzUSubx4JQXM8OO9czbcmtSfxPYheJ7atVtiYYGbVC8dIuPX4xEFXfrhW8GKdHtndrX/58Mti3VignQGHb6GA+1QKkAXe8KbsPADoUcvXUMH0mXU8FOUoJLqGLDcYZF3OJZ2ENjRrWrk2fpmpKqLJFeKAcVa5vLHoXeGeavIsZpSRhKLtib+5qtK94f9ku6kjqse7sTUQWaDRVvZzBYmZU7WwwUWEcwfTQ1uTPJvfRz0jW9DgumyZnrEuf/3eqYArF271JlFa2wX1JQj216+WNu1xVNJWBm73bcuNvypJzaw8DoB42puAak60dO1Rn7lTrSHNdjafWwqsG7sLluNTn8GbkMakrdF0euDlsRiqmHhhbIsEkj4PYpylVi6DfB+z9Qbfe6ii5uqfUQXYZvoSz5jDXYUu/IqaU/0XKuUhuCJrPVmgTDqPBkLiIZtZV2Qw5fRY8+shCiw6iIfj0B9MNBRrOumkcd1/SpOHx3sgIi4QTsIwW7Nfh3c6PaNCBdz53gTitZj2stbhHWvYdThezE9e1vU2txEWsH4cX5Goa9GxBaZDzYX45Ba9p3k5xBOh7JntkgbJSOYnF1Jv3u2S3gFDPcTuqNckCsr5vPc2lUtxA3ntSeYXiolBQMKF23HoNZ1jkCmnCjIeERXl8G31nmkQ98KdmNEzWeP7XZVuExl+6NGGxLNudYHvoHUuSJPc9SpAfzQyBi2vSUJikaDNHx8BLXezV56r3jtwmtgt+DXKVQjy0L9pKmUlMtrW5A+UcYAJjktMMvtSF09fqThgVXVBBGh4NR0eVlCi3AWtBCNLKnXb+3AHHSBqAWOgOhVKP7BfX1jCdznaQp2fvH2I4LmEz19smjDnHm3PyJj/+HTo9zNMh38Ol7+aPR+Opw4Ss+BlIFH+EtYy08/8OojH8WbJJ9BU8J8elao5pD3AfUq9fjZP08veJEM+7r594KzhVe+l22jIJ1ZGuvUVyKO6aJV5bVeOG5QEG+c6FTNM7+oVxy3S90ePSCwXBifVRka3lYB17Yups6WksQ+dqOYMuAqwQEV9Oq4qSPQ4D71m0Y3IyyEHF8KOXXErGApdU=
    identity.pub: AgB1OIE/ltQ0uX58THY0UdVnV+Soy2gaYhdcji8dxHE1iDGddMDBxG3fNWV6m7swFsXJjKOGN5qtKHdigUtcgDjM9LCnV9AFjQa8ku8EUCqX7BZPggxq7nN0TtiCATvdblsc7C3cRv3YEFEh/GXwX+HG+BPJqsu0X/KY2Zjo5N11+hZTMaNh4m0JO452XT+rSIoiBIC6as96QOkcDWqURJpB35cf+BSxI38VDF1ItepmijSCsFkF0Ndky3uTCFEs4+9IwnTMxKtS/AwvNeFBq5lkMjcyHANBegp+zsADpq/d0QwiR4tWNIuBXG7H0BjcMWnhSzZnNR2vH1xudG/FEf4X6JxVWAPVtgKToYifH0+/mvJ51iyBDRKFA14vzvdwfv8RCXKGODRfdy6nXQwXLzkF/ngVKG3Ncn8fTvU3E2OFcwmdfR3B9X8ivTkSn7CpSPuxKR9o5EeDaw0+6J5cCct0L55wYhXeW7nVimhmBN7dwncPAVscLviJVmsb7yYg7iUqu5cH8TVw+LzAYYGzvANMBhumMZOu3opEbl8kJAGDj7RudwXG621wrlCCTWq4Hf/PegKYP5anIcbxs4xTIqzs5JeztFgTBvs0tTNHWYJSAB34TEytftOng1OrjvNk3538MBhWVJmdTrWfjsciYZOia4SPaYU+rUowsdRt/3/lwDW9651ge7Ou9NyV3ow8eRS1SnB6vvrRsHD+Hw6Te7+xysiATzvqfcmU/YiM9wXsQFyiVudEqZ846h9u34tJZWJkishLRPPA/bjYLIVn/bKOY8o2Pt0grxC/WXjJIemukz1eqbTpjPC9Yje8wWeF08UjdjcIcwBa7e+JbW1yyLEpSuKVMEtwKz+lLYSYKgBnhNBorqEy8mcakF/F3dvUhwDTIXWaJZHplKis/2CRlYa6BOUDI+iDAa37YjM3erE+sEX8J/hfIwP6hg88YhEsGQbJ+1hP6HESUwVokr5P
    known_hosts: AgAmEPhxsmbzoKFIL7wR5EIVFbfVcLYI5qeOaLb+q5FY6xNj0LNcTagguUILp6buNoq/FhvUPINZtYD4LLQ4HGgcaJx2kT3iOJm65LcyyQOaUAWn2aouOvD8YID2Zwds+RtIOuhfSNuwYbAIEbZEXBkaWm5piZuCk/pR2cbRhNtVl0eTSNFQjPmjIRguhLhbFfcd3pSxpb4VROFgy4zMQNa86y9ROecNlKX4kGe/B78lGpzO+dePUXCRQgNB6gAEQiCowmAG+YNp4bLlquCZEVW3d2NjLmnBUdyGq25brh9er4QqPYWFmYDuO7nY1+meOgeCVArKeQLKDP+Zsmw0DOHexH+ZuTaijHQ61pEwLcezrJdOm6OAXjuP3GNfTy7ML98+r8YF0L7aM+1LfTyLMrMGqBfZ4IrjEzz0kytI+xBxfYxOUjBoNTNbayrLbRoHjyojlhvctPHG/4x7s8zbaUJJg+2vuB8t6o4Qo3Lm5SvdH9ymT93aN17bkW0FPwvZGPfI6KR3Lg3bS2zbIg6yh/t0JUE57u9NgAW+dxKoIVs8PMeKQicX9YdRjd2NySKORXTYpo+ozVuLr4G0Pi+bdUxG2Gxe9UtwG3mci8QLWogH1Wpsk7UyD1wXIsh7XoIrJQ+G3RVsPPZqCiGzs5QtjMpEbbMmwTo5MEso86YLLXIX9XyPDip90sPBYgVvpqfIJM6lmBTPJgYYNBDO2X6aMp9Kw8LspWfv7Gtg6L1AM2+iyWiXXSOgihLVmFINwKzv8PPWchngl4peeF43O/whtSCcDXYWUXbuav6rhR12u5676MLmmaQIgHmZoUw3t7jb/OXdgQrrbEVYLgjvqKxof4AUEA4JG8pFK9ybtfOQcP0zRbnBH1/MlQaNfMDQt7im3EbZDFL1c2tv2/FoConk8nsjpMfs9biLreSMRCM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: teamx-git
      namespace: flux-system
    type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: teamx
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: teamx-git
  url: ssh://git@github.com/in-the-keyhole/gitops-teamx
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: teamx-production
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./production
  prune: true
  sourceRef:
    kind: GitRepository
    name: teamx
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: teamx-staging
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: teamx
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: teamx-develop
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./develop
  prune: true
  sourceRef:
    kind: GitRepository
    name: teamx
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: teamx-production-image-update
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: teamx
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      # This can be changed to push to different branch and utilize pull request process
      branch: flux-image-updates
  update:
    path: ./production
    strategy: Setters